### ISSUE TITLE
Error using https jenkins url

### ISSUE THREAD

**Issue by FROSADO** [Taurus95/IJenkins#1]

**Comment by FROSADO** [comment]
Debugging the error appear error.innerError.code =  "UNABLE_TO_VERIFY_LEAF_SIGNATURE"

"Error: unable to verify the first certificate	at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)	at TLSSocket.emit (events.js:182:13)	at TLSSocket._finishInit (_tls_wrap.js:635:8)"
